'use strict';
const page=document.body.dataset.page;
chrome(page);
const main=$('#main');
const query=new URLSearchParams(location.search);
const state={events:[],category:query.get('category')||'nfl-football',search:query.get('q')||'',place:'',date:'',offset:0,controller:null,kind:'event',selected:null,teams:[],step:1,qty:2,threshold:'',clubLevel:false,clubs:[],clubOptions:[],homeAway:'home',alertStyle:'first',watches:[],prices:[],scans:[],filter:'all'};
const matchSummary=w=>w.kind==='team'?`${cap(w.match.slug)} · ${w.match.home_away==='any'?'Home & away':cap(w.match.home_away||'home')+' games'}`:w.kind==='date'?whenShort(w.match.date)+(w.match.city?` in ${w.match.city}`:w.match.state?` in ${w.match.state}`:''):w.label;
function layout(title,sub,body,action='') {main.innerHTML=`<div class="container page"><div class="page-heading"><div><h1>${title}</h1><p>${sub}</p></div>${action}</div>${body}</div>`;}
function stadiumArt(){return `<div class="hero-art" aria-hidden="true"><div class="ticket-art"><div class="ticket-art-top"><span>Good times ahead</span>${icon('ticket')}</div><div class="stadium"><div class="stadium-ring ring-one"></div><div class="stadium-ring ring-two"></div><div class="stadium-ring ring-three"></div><div class="field"><div class="field-center"></div><div class="endzone first">GAME</div><div class="endzone last">DAY</div><i></i><b></b></div><span class="stadium-light light-one"></span><span class="stadium-light light-two"></span></div><div class="ticket-art-bottom"><span>Your seat is out there.</span><div class="barcode"></div></div></div><div class="floating-tag">${icon('bell')} The right price. You’re in.</div></div>`;}
function explore(){
 main.innerHTML=`<div class="container"><section class="hero"><div class="hero-copy"><div class="season-label">${icon('ball')} For the love of being there</div><h1>Your next game.<br>Your kind of price.</h1><p>Pick the game. Set your budget. Get a text when tickets hit your price.</p><a class="button primary" href="./new.html">Create a ticket alert ${icon('arrow')}</a><div class="hero-note">${icon('check')} Fees included ${icon('check')} Seats together ${icon('check')} No need to keep checking</div></div>${stadiumArt()}</section><section class="explore-section" aria-labelledby="explore-title"><div class="section-heading"><div><h2 id="explore-title">Find your next one.</h2><p>The game, the gig, the night you don’t want to miss.</p></div><a class="text-link" href="./new.html?kind=team">Follow a whole team ${icon('arrow')}</a></div><div class="explore-layout"><div class="explore-main">${searchControls()}<div class="results-meta"><span id="results-count" role="status">Finding upcoming events…</span><span>Prices per ticket</span></div><div id="events">${loadingRows()}</div><button id="more-events" class="button secondary load-more" hidden>Show more events</button></div><aside class="explore-aside"><div class="playbook"><span class="playbook-icon">${icon('bell')}</span><h3>Less refreshing.<br>More being there.</h3><p>A ticket alert keeps an eye on your price, so you can get on with your day.</p><ol><li><span>Pick your event</span><small>One game, a team, or a day out.</small></li><li><span>Call your price</span><small>Your budget, with fees included.</small></li><li><span>Watch for the text</span><small>A link to the tickets when they match.</small></li></ol><a class="button white" href="./new.html">Set up an alert ${icon('arrow')}</a></div><div class="aside-note">${icon('shield')}<p><strong>You make the call.</strong> We find matching listings. You choose whether to buy on Gametime.</p></div><div class="source-note">${icon('clock')}<span>Checks target every 15 minutes near game day. <a href="./notifications.html">How delivery works</a></span></div></aside></div></section></div>`;
 bindSearch(loadEvents);$('#more-events').onclick=()=>{state.offset+=12;loadEvents(true);};loadEvents();
}
function searchControls(builder=false){return `<form class="search-bar" id="search-form" role="search"><label class="search-input">${icon('search')}<span class="sr-only">Search teams, artists, or events</span><input id="event-search" type="search" autocomplete="off" placeholder="Search a team, artist, or event" value="${esc(state.search)}"></label><button class="button primary search-submit" type="submit">Search</button></form><div class="filter-row"><label><span class="sr-only">League or category</span><select id="category"><option value="">All events</option>${['nfl-football','mlb-baseball','nba-basketball','nhl-hockey','college-football','mls-soccer','concert','comedy','theater','sports'].map(c=>`<option value="${c}" ${state.category===c?'selected':''}>${leagueName(c)}</option>`).join('')}</select></label><label><span class="sr-only">City or state</span><input id="place" type="search" placeholder="City or state" value="${esc(state.place)}"></label><label><span class="sr-only">Event date</span><input id="event-date" type="date" aria-label="Event date" min="${todayISO()}" value="${esc(state.date)}"></label><button class="text-button" id="clear-filters" type="button">Reset</button></div>${!builder?`<div class="league-tabs" aria-label="Quick category filters">${['nfl-football','mlb-baseball','nba-basketball','nhl-hockey','concert'].map(c=>`<button data-category="${c}" aria-pressed="${state.category===c}">${leagueName(c)}</button>`).join('')}</div>`:''}`;}
function bindSearch(load){
 $('#search-form').onsubmit=e=>{e.preventDefault();state.search=$('#event-search').value.trim();state.offset=0;load();};
 $('#category').onchange=e=>{state.category=e.target.value;state.offset=0;$$('[data-category]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.category===state.category));load();};
 $('#place').oninput=e=>{state.place=e.target.value.trim();clearTimeout(state.placeTimer);state.placeTimer=setTimeout(()=>{state.offset=0;load();},400);};
 $('#event-date').onchange=e=>{state.date=e.target.value;state.offset=0;load();};
 $('#clear-filters').onclick=()=>{clearTimeout(state.placeTimer);state.search='';state.place='';state.date='';state.category='';state.offset=0;$('#event-search').value='';$('#place').value='';$('#event-date').value='';$('#category').value='';$$('[data-category]').forEach(b=>b.setAttribute('aria-pressed','false'));load();};
 $$('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;$('#category').value=state.category;$$('[data-category]').forEach(x=>x.setAttribute('aria-pressed',x===b));state.offset=0;load();});
}
function catalogQuery(limit=13){
 let q=`tix_events_v?select=*&event_date=${state.date?'eq.'+state.date:'gte.'+todayISO()}&order=event_date,event_id&limit=${limit}&offset=${state.offset}`;
 if(state.category)q+='&category=eq.'+encodeURIComponent(state.category);
 // Strip PostgREST filter syntax, then quote each server-side search pattern.
 const clean=s=>s.replace(/[%*(),"\\]/g,' ').trim();
 if(state.search){const term=clean(state.search);if(term)q+='&or='+encodeURIComponent(`(name.ilike."*${term}*",slug.ilike."*${term.replace(/\s+/g,'-')}*")`);}
 if(state.place){const p=clean(state.place);q+=p.length===2?'&state=eq.'+encodeURIComponent(p.toUpperCase()):'&city=ilike.'+encodeURIComponent('*'+p+'*');}
 return q;
}
async function loadEvents(append=false){
 state.controller?.abort();const ctrl=state.controller=new AbortController();const box=$('#events');if(!append)box.innerHTML=loadingRows();
 const more=$('#more-events');if(more){more.disabled=true;more.textContent='Loading…';}
 try{
  const rows=await sbGet(catalogQuery(),{signal:ctrl.signal});if(ctrl!==state.controller)return;
  const moreAvailable=rows.length>12;rows.length=Math.min(rows.length,12);state.events=append?[...state.events,...rows]:rows;
  if(!append)box.innerHTML='';
  if(!state.events.length)box.innerHTML=`<div class="empty-state">${icon('search')}<h3>No events found.</h3><p>Try a shorter name, another date, or remove the city filter.</p><button class="button secondary" id="empty-reset">Clear filters</button></div>`;
  rows.forEach(e=>{const el=document.createElement('article');el.className='event-row';el.innerHTML=`${dateBadge(e.event_date)}<div class="event-info"><span class="event-category">${esc(leagueName(e.category))}</span><h3>${esc(cap(e.name))}</h3><p>${esc(e.venue||cap(e.venue_slug))}<span class="event-place">${esc(e.city)}, ${esc(e.state)}</span></p></div><div class="event-price">${e.min_total&&ageMinutes(e.last_seen)<120?`<strong>${money(e.min_total)}</strong><small>Last seen from</small>`:'<span>Pick your price</span>'}</div><a class="button alert-button" href="./new.html?event=${encodeURIComponent(e.event_id)}">${icon('bell')}<span>Set alert</span><span class="sr-only"> for ${esc(cap(e.name))}</span></a>`;box.appendChild(el);});
  $('#results-count').textContent=state.events.length?`${state.events.length}${moreAvailable?'+':''} upcoming events${state.place?' in '+state.place:''}`:'No upcoming matches';
  if(more){more.hidden=!moreAvailable;more.disabled=false;more.textContent='Show more events';}
  if($('#empty-reset'))$('#empty-reset').onclick=()=>$('#clear-filters').click();
 }catch(e){if(e.name==='AbortError')return;if(ctrl!==state.controller)return;box.innerHTML=errorBox(e.message);$('#retry').onclick=()=>loadEvents();$('#results-count').textContent='Events could not load';if(more)more.hidden=true;}
}
async function getHealth(){try {const rows=await sbGet('tix_state?k=in.(collector_health,notification_health)&select=k,v');return Object.fromEntries(rows.map(r=>[r.k,typeof r.v==='string'?JSON.parse(r.v):r.v]));}catch{return {};}}
async function watches(){
 layout('Your ticket alerts.','Your events, your seats, your price. We’ll keep watch.',`<div id="watch-health"></div><div class="watch-toolbar"><div class="segmented" aria-label="Filter alerts">${[['all','All alerts'],['active','Watching'],['hit','At target'],['paused','Paused']].map(([k,l])=>`<button data-filter="${k}" aria-pressed="${state.filter===k}">${l}</button>`).join('')}</div><button id="refresh-watches" class="text-button">${icon('refresh')} Refresh</button></div><div id="watches">${loadingRows(3)}</div>`,`<a class="button primary" href="./new.html">${icon('plus')} Create an alert</a>`);
 $$('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));renderWatches();});$('#refresh-watches').onclick=watches;
 try{
 const [ws,ps,ss,health]=await Promise.all([sbGet('tix_watches?select=*&order=created_at.desc'),sbGet('tix_prices?select=*&order=checked_at.desc&limit=1000'),sbGet('tix_scans?select=*&order=checked_at.desc&limit=1000').catch(()=>[]),getHealth()]);
 state.watches=ws;state.prices=ps;state.scans=ss;renderWatches();
 const h=health.collector_health;
 $('#watch-health').innerHTML=h?`<div class="health-strip ${ageMinutes(h.checked_at)>35||h.status==='error'?'attention':''}">${icon('clock')}<span>${ageMinutes(h.checked_at)>35?'Checks are delayed.':h.status==='error'?'Some checks need attention.':'Last collector run '+ago(h.checked_at).toLowerCase()+'.'} New alerts usually get their first check on the next run.</span><a href="./notifications.html">View status</a></div>`:'';
 }catch(e){$('#watches').innerHTML=errorBox(e.message);$('#retry').onclick=watches;}
}
function watchLatest(w){
 const scans=state.scans.filter(s=>s.watch_id===w.id);const byEvent=Object.fromEntries(scans.map(s=>[s.event_id,s]));const seen=new Set();
 const latest=state.prices.filter(p=>{if(p.watch_id!==w.id||new Date(p.checked_at)<new Date(w.criteria_updated_at||w.created_at))return false;const key=p.event_id+'|'+p.club;if(seen.has(key))return false;seen.add(key);const scan=byEvent[p.event_id];return p.qty===w.qty&&ageMinutes(p.checked_at)<120&&(!scan||(scan.outcome==='ok'&&new Date(p.checked_at)>=new Date(scan.checked_at)-1000));});
 const rows=latest.filter(p=>p.watch_id===w.id);return rows.sort((a,b)=>a.price_cents-b.price_cents);
}
function renderWatches(){
 const box=$('#watches');const ws=state.watches.filter(w=>state.filter==='all'||(state.filter==='active'&&w.active)||(state.filter==='paused'&&!w.active)||(state.filter==='hit'&&w.active&&watchLatest(w).some(p=>p.price_cents<=w.threshold_cents)));
 if(!ws.length){box.innerHTML=`<div class="empty-state watch-empty"><span class="empty-ticket">${icon('ticket')}</span><h2>${state.watches.length?'No alerts in this view.':'Good seats start with a game plan.'}</h2><p>${state.watches.length?'Choose another filter to see your saved alerts.':'Choose an event and your maximum price. Your first ticket alert takes about a minute to set up.'}</p><a class="button primary" href="./new.html">${icon('plus')} Create an alert</a></div>`;return;}
 box.innerHTML='<div class="watch-grid"></div>';const grid=$('.watch-grid');
 for(const w of ws){const rows=watchLatest(w),p=rows[0],hit=w.active&&p&&p.price_cents<=w.threshold_cents;const recent=state.scans.filter(s=>s.watch_id===w.id)[0];const status=!w.active?'Paused':hit?'At your price':recent?.outcome==='failed'?'Check delayed':'Watching';
 const article=document.createElement('article');article.className='watch-card'+(hit?' is-hit':'');article.innerHTML=`<div class="watch-card-head"><span class="sport-stamp">${icon(w.kind==='team'?'ball':'ticket')}</span><span class="badge ${hit?'green':!w.active?'neutral':recent?.outcome==='failed'?'amber':'blue'}">${w.active?'<i></i>':''}${status}</span></div><h2>${esc(w.label)}</h2><p class="watch-detail">${esc(w.kind==='team'?matchSummary(w):w.kind==='date'?matchSummary(w):'One event')} · ${w.qty} ${w.qty===1?'ticket':'tickets together'}</p><div class="watch-score"><div><span>Your target</span><strong>${money(w.threshold_cents)}</strong><small>per ticket, fees included</small></div><div><span>Latest match</span><strong class="${hit?'hit-text':''}">${p?money(p.price_cents):'—'}</strong><small>${p?ago(p.checked_at):recent?.outcome==='failed'?'Could not check listings':recent?'No matching tickets':'Waiting for first check'}</small></div></div>${p?`<p class="price-context">${esc(p.club)} · ${esc(p.event_label||'')}${hit?`<br><strong>${money(w.threshold_cents-p.price_cents)} below your limit</strong>`:''}</p>`:'<p class="price-context">We’ll show a price when a recent listing matches your seat preferences.</p>'}<div class="watch-options"><span>${icon('people')}${w.match?.club_level?(w.clubs.length?esc(w.clubs.join(', ')):'Any club section'):'Any section'}</span><span>${icon('bell')}${w.alert_style==='repeat'?'Hourly while at target':'First match per event & section'}</span></div>${p&&safeUrl(p.listing_url)?`<a class="button ${hit?'primary':'secondary'} full" href="${esc(safeUrl(p.listing_url))}" target="_blank" rel="noopener">View tickets on Gametime ${icon('arrow')}</a>`:''}<div class="card-actions"><a href="./new.html?edit=${w.id}">Edit alert</a><button data-action="pause">${w.active?'Pause':'Resume'}</button><button data-action="delete" aria-label="Delete ${esc(w.label)}">Delete</button></div>`;
 article.querySelector('[data-action="pause"]').onclick=async e=>{e.target.disabled=true;try{const out=await sbWrite('PATCH','tix_watches?id=eq.'+w.id,{active:!w.active});if(!out.length)throw new Error('This alert no longer exists. Refresh the page.');w.active=!w.active;renderWatches();toast(w.active?'Alert resumed.':'Alert paused.');}catch(err){toast(err.message);e.target.disabled=false;}};
 article.querySelector('[data-action="delete"]').onclick=()=>{showDialog('Delete this alert?',`<p><strong>${esc(w.label)}</strong></p><p>This stops the alert and removes its price history. This cannot be undone.</p><div class="dialog-actions"><button class="button secondary" id="cancel-delete">Keep alert</button><button class="button danger" id="confirm-delete">Delete alert</button></div><div id="delete-error"></div>`);$('#cancel-delete').onclick=()=>$('#dialog').close();$('#confirm-delete').onclick=async e=>{e.target.disabled=true;try{await sbWrite('DELETE','tix_watches?id=eq.'+w.id);state.watches=state.watches.filter(x=>x.id!==w.id);$('#dialog').close();renderWatches();toast('Alert deleted.');}catch(err){$('#delete-error').innerHTML=errorBox(err.message,'');e.target.disabled=false;}};};grid.appendChild(article);
 }
}
async function builder(){
 state.kind=query.get('kind')==='team'?'team':'event';
 if(query.has('edit')||query.has('event')){
 layout('Getting your alert ready.','One moment while we load the details.',loadingRows(2));
 try {
 if(query.has('edit')){const [w]=await sbGet('tix_watches?id=eq.'+encodeURIComponent(query.get('edit'))+'&select=*');if(!w)throw new Error('This alert was removed. Start a new alert from Find events.');state.edit=w;state.kind=w.kind;state.qty=w.qty;state.threshold=(w.threshold_cents/100).toString();state.clubs=w.clubs||[];state.clubLevel=w.match.club_level??!!w.clubs.length;state.homeAway=w.match.home_away||'home';state.alertStyle=w.alert_style;state.label=w.label;state.category=w.match.category||state.category;if(w.kind==='team')state.selected={team:w.match.slug};else if(w.kind==='date')state.selected={date:w.match.date,city:w.match.city,state:w.match.state,venue_slug:w.match.venue_slug};else{const [event]=await sbGet('tix_events_v?event_id=eq.'+encodeURIComponent(w.match.event_ids[0])+'&select=*');if(!event)throw new Error('This event is no longer in the catalog. Create a new alert for an upcoming event.');state.selected=event;}}
 else{const [event]=await sbGet('tix_events_v?event_id=eq.'+encodeURIComponent(query.get('event'))+'&select=*');if(!event)throw new Error('This event is no longer available. Find another event to watch.');state.selected=event;}
 state.step=2;renderBuilder();loadClubs();
 }catch(e){layout('Let’s find another event.','Your alert has not changed.',errorBox(e.message,'')+'<a class="button primary" href="./new.html">Start a new alert</a>');}return;
 }renderBuilder();
}
function selectionTitle(){return state.kind==='team'?cap(state.selected?.team):state.kind==='date'?whenShort(state.selected?.date)+(state.selected?.city?' in '+state.selected.city:state.selected?.state?' in '+state.selected.state:''):cap(state.selected?.name||'Choose an event');}
function summary(){const total=Math.round(Number(state.threshold)*100)*state.qty;return `<aside class="builder-summary"><div class="summary-ticket"><div class="summary-top">${icon('ticket')}<span>Your game plan</span></div><h3>${esc(state.selected?selectionTitle():'A great night starts here.')}</h3><p>${esc(state.kind==='event'&&state.selected?whenShort(state.selected.event_date)+' · '+(state.selected.venue||cap(state.selected.venue_slug)):state.kind==='team'?'Follow the schedule. Catch the right price.':'Choose what you want to see, then set your limit.')}</p><div class="summary-lines"><div><span>Tickets together</span><strong>${state.qty}</strong></div><div><span>Maximum per ticket</span><strong>${state.threshold?money(Math.round(Number(state.threshold)*100)):'Your call'}</strong></div><div><span>Total ticket budget</span><strong>${state.threshold?money(total):'—'}</strong></div></div><div class="summary-bottom">${icon('check')} Fees included in your limit</div></div><div class="aside-note">${icon('bell')}<p>Texts go to the destination already configured for this board. <a href="./notifications.html">View delivery status</a></p></div></aside>`;}
function renderBuilder(){
 layout(state.edit?'Fine-tune your alert.':'Be there. At your price.','A few details now. A heads-up when the right tickets show up.',`<ol class="steps" aria-label="Alert setup progress">${['Pick your event','Set your price','Review & save'].map((s,i)=>`<li class="${state.step===i+1?'current':state.step>i+1?'complete':''}" ${state.step===i+1?'aria-current="step"':''}><span>${state.step>i+1?icon('check'):i+1}</span>${s}</li>`).join('')}</ol><div class="builder-layout"><section class="builder-panel" id="builder-panel"></section><div id="builder-summary">${summary()}</div></div>`);
 if(state.step===1)pickStep();else if(state.step===2)priceStep();else reviewStep();
}
function pickStep(){
 $('#builder-panel').innerHTML=`<div class="panel-heading"><h2>What’s on your radar?</h2><p>Track one event, a team, or everything on a date.</p></div><div class="kind-grid">${[['event','ticket','One event','A game, concert, or show'],['team','ball','A team','Home, away, or both'],['date','clock','A day out','See what fits your plans']].map(([k,i,t,s])=>`<button data-kind="${k}" aria-pressed="${state.kind===k}">${icon(i)}<strong>${t}</strong><span>${s}</span></button>`).join('')}</div><div id="picker"></div>`;
 $$('[data-kind]').forEach(b=>b.onclick=()=>{state.kind=b.dataset.kind;state.selected=null;state.clubs=[];state.clubLevel=false;state.controller?.abort();pickStep();});
 if(state.kind==='event'){$('#picker').innerHTML=`${searchControls(true)}<div class="results-meta"><span id="results-count" role="status"></span></div><div id="events"></div><button id="more-events" class="button secondary load-more" hidden>Show more events</button>`;bindSearch(pickerEvents);$('#more-events').onclick=()=>{state.offset+=12;pickerEvents(true);};state.offset=0;pickerEvents();}
 else if(state.kind==='team')teamPicker();else datePicker();
}
async function pickerEvents(append=false){await loadEvents(append);if(!$('#events'))return;$$('.alert-button',$('#events')).forEach(a=>{a.innerHTML=`Select ${icon('arrow')}<span class="sr-only">${esc(a.closest('article').querySelector('h3').textContent)}</span>`;a.onclick=e=>{e.preventDefault();const id=new URL(a.href).searchParams.get('event');state.selected=state.events.find(x=>x.event_id===id);state.step=2;renderBuilder();loadClubs();window.scrollTo({top:0,behavior:'instant'});};});}
async function teamPicker(){
 $('#picker').innerHTML=`<label class="field-label" for="team-league">League</label><select id="team-league">${['nfl-football','mlb-baseball','nba-basketball','nhl-hockey','college-football','mls-soccer'].map(c=>`<option value="${c}" ${c===state.category?'selected':''}>${leagueName(c)}</option>`).join('')}</select><label class="field-label" for="team-search">Find your team</label><div class="search-input standalone">${icon('search')}<input id="team-search" type="search" placeholder="Type a team name"></div><div id="team-options" class="team-grid">${loadingRows(2)}</div>`;
 state.category=$('#team-league').value;$('#team-league').onchange=e=>{state.category=e.target.value;teamPicker();};
 const category=state.category;
 try{const teams=await sbGet('tix_teams_v?category=eq.'+encodeURIComponent(category)+'&select=team,events&order=team');if(state.kind!=='team'||category!==state.category)return;
 state.teams=teams.filter(t=>!/(^|-)vs(-|$)|hall-of-fame|super-bowl|all-star|pro-bowl/i.test(t.team));
 const draw=()=>{const filter=$('#team-search').value.trim().toLowerCase();const shown=state.teams.filter(t=>cap(t.team).toLowerCase().includes(filter));$('#team-options').innerHTML=shown.length?shown.map(t=>`<button class="team-option" data-team="${esc(t.team)}">${icon('ball')}<span>${esc(cap(t.team))}</span>${icon('arrow')}</button>`).join(''):'<p class="muted">No matching teams. Try another name or league.</p>';$$('[data-team]').forEach(b=>b.onclick=()=>{state.selected={team:b.dataset.team};state.step=2;renderBuilder();loadClubs();});};$('#team-search').oninput=draw;draw();
 }catch(e){$('#team-options').innerHTML=errorBox(e.message);$('#retry').onclick=teamPicker;}
}
function datePicker(){
 $('#picker').innerHTML=`<form id="date-form"><label class="field-label" for="day-out">Which day?</label><input id="day-out" type="date" required min="${todayISO()}" value="${state.selected?.date||''}"><div class="two-fields"><div><label class="field-label" for="day-city">City <span>optional</span></label><input id="day-city" placeholder="e.g. Minneapolis" value="${esc(state.selected?.city||'')}"></div><div><label class="field-label" for="day-state">State or province <span>optional</span></label><input id="day-state" placeholder="e.g. MN" maxlength="2" pattern="[A-Za-z]{2}" value="${esc(state.selected?.state||'')}"></div></div><p class="field-help">Track any event on this date. Add a city or state to keep the search close to your plans.</p><button class="button primary" type="submit">Continue ${icon('arrow')}</button><div id="day-error"></div></form>`;
 $('#date-form').onsubmit=async e=>{e.preventDefault();const b=$('#date-form button');b.disabled=true;const selected={date:$('#day-out').value,city:$('#day-city').value.trim(),state:$('#day-state').value.trim().toUpperCase()};try{let q='tix_events_v?select=event_id&event_date=eq.'+selected.date+'&limit=1';if(selected.city)q+='&city=ilike.'+encodeURIComponent(selected.city);if(selected.state)q+='&state=eq.'+encodeURIComponent(selected.state);const rows=await sbGet(q);if(!rows.length)throw new Error('No events are listed for this date and place. Try a different day or remove the city.');state.selected=selected;state.step=2;renderBuilder();}catch(err){$('#day-error').innerHTML=errorBox(err.message,'');b.disabled=false;}};
}
function priceStep(){
 $('#builder-panel').innerHTML=`<button class="text-button back-button" id="back-pick">${icon('arrow')} Change event</button><div class="panel-heading"><h2>Make it your kind of ticket.</h2><p>${esc(selectionTitle())}</p></div><form id="price-form">${state.kind==='team'?`<fieldset><legend>Which games?</legend><div class="segmented">${[['home','Home games'],['away','Away games'],['any','Home & away']].map(([v,l])=>`<label class="radio-choice"><input type="radio" name="home-away" value="${v}" ${state.homeAway===v?'checked':''}><span>${l}</span></label>`).join('')}</div></fieldset>`:''}<div class="price-fields"><div><label class="field-label" for="qty">Tickets together</label><div class="quantity-control"><button type="button" id="qty-minus" aria-label="One fewer ticket">−</button><input id="qty" type="number" min="1" max="8" required value="${state.qty}" aria-describedby="qty-help"><button type="button" id="qty-plus" aria-label="One more ticket">+</button></div><p class="field-help" id="qty-help">Only listings that sell your exact quantity.</p></div><div><label class="field-label" for="target">Maximum per ticket</label><div class="currency-input"><span>$</span><input type="number" id="target" min="1" max="50000" step="0.01" inputmode="decimal" required placeholder="150" value="${esc(state.threshold)}" aria-describedby="target-help"></div><p class="field-help" id="target-help">Fees included. Text at this price or less.</p></div></div><div id="price-reference"></div><fieldset><legend>Where do you want to sit?</legend><div class="seat-choices"><label class="radio-card"><input type="radio" name="seat-type" value="any" ${!state.clubLevel?'checked':''}><span><strong>Any section</strong><small>The best match anywhere in the venue.</small></span></label><label class="radio-card"><input type="radio" name="seat-type" value="club" ${state.clubLevel?'checked':''}><span><strong>Club seats only</strong><small>Match sections listed as a club.</small></span></label></div><div id="club-options"></div></fieldset><fieldset><legend>How often should we text?</legend><label class="radio-card"><input type="radio" name="alert-style" value="first" ${state.alertStyle==='first'?'checked':''}><span><strong>First match only</strong><small>One text per event and matching section. No reminders.</small></span></label><label class="radio-card"><input type="radio" name="alert-style" value="repeat" ${state.alertStyle==='repeat'?'checked':''}><span><strong>Keep me posted</strong><small>At most once an hour per event and section while the price qualifies.</small></span></label></fieldset><label class="field-label" for="alert-name">Alert name <span>optional</span></label><input id="alert-name" maxlength="140" placeholder="${esc(selectionTitle())}" value="${esc(state.label||'')}"><div class="form-bottom"><p>${icon('shield')} You decide when to buy.</p><button class="button primary" type="submit">Review alert ${icon('arrow')}</button></div></form>`;
 const sync=()=>{state.qty=Number($('#qty').value)||1;state.threshold=$('#target').value;state.label=$('#alert-name').value;$('#builder-summary').innerHTML=summary();$('#qty-minus').disabled=state.qty<=1;$('#qty-plus').disabled=state.qty>=8;};
 $('#qty-minus').onclick=()=>{$('#qty').value=Math.max(1,state.qty-1);sync();};$('#qty-plus').onclick=()=>{$('#qty').value=Math.min(8,state.qty+1);sync();};$('#qty').oninput=sync;$('#target').oninput=sync;$('#alert-name').oninput=sync;
 $$('[name="seat-type"]').forEach(r=>r.onchange=()=>{state.clubLevel=r.value==='club';if(!state.clubLevel)state.clubs=[];renderClubOptions();});
 $$('[name="alert-style"]').forEach(r=>r.onchange=()=>state.alertStyle=r.value);
 $$('[name="home-away"]').forEach(r=>r.onchange=()=>{state.homeAway=r.value;state.clubs=[];loadClubs();});
 $('#back-pick').onclick=()=>{sync();state.step=1;renderBuilder();};
 $('#price-form').onsubmit=e=>{e.preventDefault();sync();if(!Number.isInteger(state.qty)||state.qty<1||state.qty>8)return;state.step=3;renderBuilder();window.scrollTo({top:0,behavior:'instant'});};renderClubOptions();sync();
 if(state.kind==='event'&&state.selected.min_total&&ageMinutes(state.selected.last_seen)<120)$('#price-reference').innerHTML=`<div class="reference-price">${icon('chart')}<p>Event prices last seen from <strong>${money(state.selected.min_total)}</strong>, ${ago(state.selected.last_seen).toLowerCase()}. This is a reference; your seat quantity and section may cost more.</p></div>`;
}
async function loadClubs(){
 const selection=state.selected;state.clubOptions=[];
 try{let venue=selection?.venue_slug;if(state.kind==='team'&&state.homeAway==='home'){const rs=await sbGet('tix_events_v?category=eq.'+encodeURIComponent(state.category)+'&slug=ilike.'+encodeURIComponent('*-at-'+state.selected.team)+'&event_date=gte.'+todayISO()+'&select=venue_slug&limit=100');const counts={};rs.forEach(r=>{if(r.venue_slug)counts[r.venue_slug]=(counts[r.venue_slug]||0)+1;});venue=Object.keys(counts).sort((a,b)=>counts[b]-counts[a])[0];}if(state.kind==='team'&&state.homeAway!=='home')venue=null;
 if(venue){const [r]=await sbGet('tix_venue_clubs?venue_slug=eq.'+encodeURIComponent(venue)+'&select=clubs');if(state.selected!==selection)return;state.clubOptions=r?.clubs||[];}
 }catch{}if(state.step===2&&$('#club-options'))renderClubOptions();
}
function renderClubOptions(){const box=$('#club-options');if(!box)return;if(!state.clubLevel){box.innerHTML='';return;}box.innerHTML=state.clubOptions.length?`<label class="field-label" for="club-choice">Club section</label><select id="club-choice"><option value="">Any club section</option>${state.clubOptions.map(c=>`<option value="${esc(c.group)}" ${state.clubs.includes(c.group)?'selected':''}>${esc(c.group)}</option>`).join('')}</select><p class="field-help">Club names come from actual listings. Availability varies by event.</p>`:`<div class="notice subtle">${icon('info')}<p>We’ll match any section labeled “club” by Gametime. ${state.kind==='team'&&state.homeAway!=='home'?'Club names vary across away venues.':'Specific club names will appear once a venue has been checked.'}</p></div>`;if($('#club-choice'))$('#club-choice').onchange=e=>state.clubs=e.target.value?[e.target.value]:[];}
function makeWatch(){const match={club_level:state.clubLevel};if(state.kind==='event'){match.event_ids=[state.selected.event_id];match.event_date=state.selected.event_date;}if(state.kind==='team'){Object.assign(match,{slug:state.selected.team,category:state.category,home_away:state.homeAway});}if(state.kind==='date'){Object.assign(match,{date:state.selected.date});for(const k of ['city','state','venue_slug'])if(state.selected[k])match[k]=state.selected[k];}return {kind:state.kind,label:state.label?.trim()||selectionTitle(),match,clubs:state.clubLevel?state.clubs:[],qty:state.qty,threshold_cents:Math.round(Number(state.threshold)*100),alert_style:state.alertStyle,active:state.edit?state.edit.active:true};}
function reviewStep(){
 const w=makeWatch();$('#builder-panel').innerHTML=`<button class="text-button back-button" id="back-price">${icon('arrow')} Change preferences</button><div class="panel-heading"><h2>Looks like a game plan.</h2><p>Check the details, then let us keep watch.</p></div><dl class="review-list"><div><dt>Watching</dt><dd>${esc(selectionTitle())}${state.kind==='team'?'<small>'+esc(state.homeAway==='any'?'Home and away games':cap(state.homeAway)+' games')+'</small>':''}</dd></div><div><dt>Tickets</dt><dd>${state.qty} ${state.qty===1?'ticket':'tickets together'}</dd></div><div><dt>Text me at</dt><dd>${money(w.threshold_cents)} or less per ticket<small>${money(w.threshold_cents*state.qty)} total ticket budget, fees included</small></dd></div><div><dt>Sections</dt><dd>${state.clubLevel?esc(state.clubs.join(', ')||'Any club section'):'Any section'}</dd></div><div><dt>Text frequency</dt><dd>${state.alertStyle==='repeat'?'At most hourly while at target':'First match per event and section'}</dd></div></dl><div class="notice subtle">${icon('bell')}<div><strong>Sent to your configured text destination</strong><p>First check is usually on the next scheduled run. Schedules and carrier delivery can be delayed.</p></div></div><p class="privacy-note">This is a shared personal board. Alert names, events, and prices are visible to anyone with the site link. Keep personal details out of alert names.</p><button class="button primary full" id="save-alert">${icon('bell')}${state.edit?'Save changes':'Create alert'}</button><div id="save-error"></div>`;
 $('#back-price').onclick=()=>{state.step=2;renderBuilder();};$('#save-alert').onclick=saveAlert;
}
async function saveAlert(){
 const b=$('#save-alert');b.disabled=true;b.textContent='Saving your alert…';$('#save-error').innerHTML='';
 try{const w=makeWatch();let saved;if(state.edit){saved=await sbWrite('PATCH','tix_watches?id=eq.'+state.edit.id,w);if(!saved.length)throw new Error('This alert no longer exists. Create a new alert.');}else{
 const all=await sbGet('tix_watches?select=*');const dup=all.find(x=>x.kind===w.kind&&x.qty===w.qty&&x.threshold_cents===w.threshold_cents&&JSON.stringify(x.clubs||[])===JSON.stringify(w.clubs)&&x.match.slug===w.match.slug&&x.match.category===w.match.category&&x.match.date===w.match.date&&x.match.city===w.match.city&&x.match.state===w.match.state&&x.match.venue_slug===w.match.venue_slug&&JSON.stringify(x.match.event_ids)===JSON.stringify(w.match.event_ids)&&x.match.home_away===w.match.home_away&&!!x.match.club_level===!!w.match.club_level&&x.alert_style===w.alert_style);
 if(dup){showDialog('You already have this alert.',`<p>${esc(dup.label)} is ${dup.active?'already watching':'paused'}. You can change it from My alerts.</p><a class="button primary" href="./watches.html">View my alerts</a>`);b.disabled=false;b.textContent='Create alert';return;}
 saved=await sbWrite('POST','tix_watches',[w]);}
 main.innerHTML=`<div class="container success-page"><div class="success-symbol">${icon('check')}</div><h1>${state.edit?'Your alert is updated.':'You’re on the list.'}</h1><p>${esc(w.label)}</p><div class="success-summary"><strong>${money(w.threshold_cents)} or less</strong><span>per ticket · ${w.qty} ${w.qty===1?'ticket':'tickets together'} · fees included</span></div><p class="muted">${!w.active?'This alert is still paused. Resume it from My alerts when you’re ready.':'We’ll check for matching tickets on the next scheduled run and text the configured destination when a price qualifies.'}</p><div class="success-actions"><a class="button primary" href="./watches.html">See my alerts ${icon('arrow')}</a><a class="button secondary" href="./new.html">Create another alert</a></div><a class="text-link" href="./notifications.html">Check notification status</a></div>`;window.scrollTo({top:0,behavior:'instant'});
 }catch(e){$('#save-error').innerHTML=errorBox(e.message,'');b.disabled=false;b.textContent=state.edit?'Save changes':'Create alert';}
}
async function activity(){
 layout('Every check. Every heads-up.','See what we found and whether your text was accepted for delivery.',`<div class="activity-tabs segmented"><button data-activity="alerts" aria-pressed="true">Text alerts</button><button data-activity="prices" aria-pressed="false">Price history</button></div><div id="activity-content">${loadingRows()}</div>`,`<button id="refresh-activity" class="button secondary">${icon('refresh')} Refresh</button>`);
 let kind='alerts';const draw=async()=>{const box=$('#activity-content');box.innerHTML=loadingRows();try{const [rows,ws]=await Promise.all([sbGet(kind==='alerts'?'tix_alerts?select=*&order=sent_at.desc&limit=100':'tix_prices?select=*&order=checked_at.desc&limit=100'),sbGet('tix_watches?select=id,label')]);const names=Object.fromEntries(ws.map(w=>[w.id,w.label]));if(!rows.length){box.innerHTML=`<div class="empty-state">${icon(kind==='alerts'?'bell':'chart')}<h2>${kind==='alerts'?'No text alerts yet.':'Your price history starts here.'}</h2><p>${kind==='alerts'?'When tickets match your budget, the delivery result will appear here.':'Once a saved alert finds a matching listing, its checked price appears here.'}</p><a class="button primary" href="./new.html">Create an alert</a></div>`;return;}box.innerHTML=`<div class="activity-list">${rows.map(r=>{const url=safeUrl(r.listing_url);return `<article class="activity-row"><span class="activity-icon ${r.status==='failed'?'failed':''}">${icon(kind==='alerts'?'bell':'chart')}</span><div><h3>${esc(names[r.watch_id]||r.event_label||'Ticket alert')}</h3><p>${esc(r.club)} · ${r.qty} ${r.qty===1?'ticket':'tickets'} · ${whenShort(r.sent_at||r.checked_at)} at ${new Date(r.sent_at||r.checked_at).toLocaleTimeString('en-US',{hour:'numeric',minute:'2-digit'})}</p>${kind==='alerts'?`<span class="badge ${r.status==='failed'?'amber':'green'}">${r.status==='failed'?'Send failed — will retry':'Accepted for delivery'}</span>`:''}</div><div class="activity-price"><strong>${money(r.price_cents)}</strong><small>per ticket</small>${url?`<a href="${esc(url)}" target="_blank" rel="noopener">View listing ${icon('arrow')}</a>`:''}</div></article>`;}).join('')}</div><p class="field-help">Showing the latest ${rows.length} records. These are historical prices; availability can change.</p>`;}catch(e){box.innerHTML=errorBox(e.message);$('#retry').onclick=draw;}};
 $$('[data-activity]').forEach(b=>b.onclick=()=>{kind=b.dataset.activity;$$('[data-activity]').forEach(x=>x.setAttribute('aria-pressed',x===b));draw();});$('#refresh-activity').onclick=draw;draw();
}
async function notifications(){
 layout('The heads-up that matters.','Your alert is only useful if you know where it’s going.',`<div class="notification-layout"><section class="settings-panel"><div class="settings-title"><span class="setting-icon">${icon('bell')}</span><div><h2>Text message alerts</h2><p>The destination configured for this board</p></div></div><div id="delivery-health">${loadingRows(1)}</div><div class="settings-divider"></div><h3>When will I get a text?</h3><p>When a checked listing has your exact number of tickets and costs at or below your per-ticket limit, fees included.</p><dl class="schedule-list"><div><dt>Events within 7 days</dt><dd>Target: every 15 minutes</dd></div><div><dt>Events more than 7 days away</dt><dd>Target: hourly</dd></div></dl><p class="field-help">Checks are scheduled, not instant. Busy periods, the ticket provider, and the carrier can delay an alert. First-match alerts are sent once per event and section; repeat alerts are limited to about once an hour.</p><a class="button primary" href="./watches.html">Manage my alerts ${icon('arrow')}</a></section><aside><div class="settings-panel"><h3>Not seeing your text?</h3><ol class="troubleshoot"><li>Make sure your alert is watching, not paused.</li><li>Check Activity for a matching price and the send result.</li><li>Check your phone’s spam or blocked messages.</li></ol><p>“Accepted for delivery” means the mail server accepted the message. It does not confirm that the carrier delivered it to your phone.</p><a class="text-link" href="./ledger.html">View text activity ${icon('arrow')}</a></div><div class="aside-note">${icon('shield')}<p>Your destination and mail credentials stay on the server. This shared personal board does not collect phone numbers.</p></div></aside></div>`,`<button class="button secondary" id="refresh-status">${icon('refresh')} Refresh status</button>`);
 $('#refresh-status').onclick=notifications;const h=await getHealth();const c=h.collector_health,n=h.notification_health;
 $('#delivery-health').innerHTML=`<div class="delivery-state"><span class="status-dot ${c?.sms_configured?'green':'amber'}"></span><div><strong>${c?.sms_configured?'Text destination configured':'Delivery configuration not yet verified'}</strong><p>${c?.sms_configured?'Uses the existing text destination for this board.':'The next collector run will report its configuration here.'}</p></div></div><div class="delivery-state"><span class="status-dot ${n?.status==='accepted'?'green':'amber'}"></span><div><strong>${n?n.status==='accepted'?'Last send accepted':'Last send failed':'No delivery attempt recorded'}</strong><p>${n?`${ago(n.checked_at)}${n.test?' · Test message':''}. ${n.status==='accepted'?'Check your phone to confirm receipt.':'The collector will retry qualifying alerts on a later check.'}`:'A qualifying ticket alert or a delivery test will show a result here.'}</p></div></div><div class="delivery-state"><span class="status-dot ${c&&ageMinutes(c.checked_at)<35&&c.status!=='error'?'green':'amber'}"></span><div><strong>${c?ageMinutes(c.checked_at)>35?'Collector check is overdue':c.status==='error'?'Collector needs attention':'Collector checked '+ago(c.checked_at).toLowerCase():'Waiting for collector status'}</strong><p>${c?`${c.checked_events||0} events checked on the last run${c.failed_events?', '+c.failed_events+' could not be checked':''}.`:'Status will appear after the first updated collector run.'}</p></div></div>`;
}
({explore,watches,new:builder,activity,notifications}[page]||explore)();
